apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    component: react
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    component: react
